name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        working-directory: finishes
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test --all --locked
      - run: cargo install cargo-dist --locked
      - run: cargo dist build
